// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeoiyRVbSR4UtOIZFhTrDjKFPsZaMnvA8',
    appId: '1:423990169102:web:700212ff76fad128fd765f',
    messagingSenderId: '423990169102',
    projectId: 'mezaan-3baaf',
    authDomain: 'mezaan-3baaf.firebaseapp.com',
    storageBucket: 'mezaan-3baaf.firebasestorage.app',
    measurementId: 'G-ZCGV59YSZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNV0LT8TgNJPnufHT0Mto5nkAdYX7pXY',
    appId: '1:423990169102:android:c87acaf4cc7aa5ddfd765f',
    messagingSenderId: '423990169102',
    projectId: 'mezaan-3baaf',
    storageBucket: 'mezaan-3baaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZ7v1pnHIzODgrYniqPB6DdrC9n6W9Wc',
    appId: '1:423990169102:ios:6f2a5eda58a87a46fd765f',
    messagingSenderId: '423990169102',
    projectId: 'mezaan-3baaf',
    storageBucket: 'mezaan-3baaf.firebasestorage.app',
    iosBundleId: 'com.example.mezaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZ7v1pnHIzODgrYniqPB6DdrC9n6W9Wc',
    appId: '1:423990169102:ios:6f2a5eda58a87a46fd765f',
    messagingSenderId: '423990169102',
    projectId: 'mezaan-3baaf',
    storageBucket: 'mezaan-3baaf.firebasestorage.app',
    iosBundleId: 'com.example.mezaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeoiyRVbSR4UtOIZFhTrDjKFPsZaMnvA8',
    appId: '1:423990169102:web:9c7770f4a9b9b214fd765f',
    messagingSenderId: '423990169102',
    projectId: 'mezaan-3baaf',
    authDomain: 'mezaan-3baaf.firebaseapp.com',
    storageBucket: 'mezaan-3baaf.firebasestorage.app',
    measurementId: 'G-J1FDWRZP5E',
  );
}
